version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "monthly"
